### ISSUE TITLE
Example is not working. 

### ISSUE THREAD

**Issue by nurdymuny** [afang/hyperlapse.js#1]
Hi

I tried to work with hyperlapse example (viewer.html). It shows message calculating route on pressing generate button. But nothing is happening after that.Please provide solution.

Regards

**Comment by afang** [comment]
It takes some time to generate the hyperlapse (depending on its length).

**Comment by nurdymuny** [comment]
Hi 

I tried it with short length, but its not working. It will be helpful if you can post some video showing working example.May be i am setting some parameter wrong.

thanks

**Comment by afang** [comment]
http://codepen.io/afang/pen/GpxqLQ

**Comment by nurdymuny** [comment]
Thanks for the link. i will check it out
