### ISSUE TITLE
How to stop when it reaches the destination.

### ISSUE THREAD

**Issue by acenova** [afang/hyperlapse.js#2]
Hi,

When I execute simple.html. it never ends. I want it run just once.
Can you tell me how to do it?

Thank you!

**Comment by afang** [comment]
The docs are included in the repo, you should look for a `loop` property and set that to `false`.

**Comment by acenova** [comment]
thank you. i will check it out.

**Comment by afang** [comment]
Closing this as I'm assuming you got it :)
