### ISSUE TITLE
Output Image Files for Video 

### ISSUE THREAD

**Issue by ZFilmz247** [afang/hyperlapse.js#5]
Andy,

I have the code working, and I am able to create videos within my web browser.

How do you output the images for video editing?  I would like to create a Youtube Video using this footage.

Thanks,
Zach

**Comment by afang** [comment]
The video is rendered on an HTML5 canvas. You’ll need an mp4 format to
upload to Youtube so just use a screen recorder.

**Comment by mmehrle** [comment]
A screen recorder is not exactly efficient as it'll interpolate and add 
unnecessary frames. It would be better if there was an option to output 
to an mp4 format at the proper frame rate.

**Comment by afang** [comment]
That isn’t possible currently but you could try hacking on Hyperlapse.
Maybe other Three.js projects have done it.
